version: '3.8'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
  server:
    build: ./server
    ports:
      - '5000:5000'
      - '3002:3002'
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
